Vagrant.configure("2") do |config|
  config.vm.box = "edemaio/quant-dev-py3"
  config.vm.box_version = "1.0.0"
  config.vm.provider "virtualbox" do |vb|
  vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  config.vm.provider :virtualbox do |vb|
  vb.gui = true
end
end
end